name: Deploy Package to Github
on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            skip-tests:
                type: boolean
                description: Skip Tests
                required: true
                default: true
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
            - run: npm ci
            - run: |
                  echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
